---
- hosts: testhost
  #vars:
  #  - nginx_port: 88
  tasks:
    - name: install epel
      yum: name=epel-release state=present

    - name: copy nginx.repo
      copy: src=/etc/yum.repos.d/nginx.repo dest=/etc/yum.repos.d/nginx.repo

    - name: install nginx package
      yum: name=nginx state=present
      tags:
       - absent

    - name: copy nginx.conf 
      template: src=/root/playbook/templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
      notify:
       - restart nginx

    - name: copy conf.d/default
      template: src=/root/playbook/templates/default.conf.j2 dest=/etc/nginx/conf.d/default.conf
      notify:
       - restart nginx

    - name: start nginx service
      service: name=nginx state=started
  
  handlers:
   - name: restart nginx
     service: name=nginx state=restarted
